scoreboard players set @a[scores={flashlight=2}] flashlight 0

execute at @a as @a run fill ~20 ~20 ~20 ~-20 ~-5 ~-20 air replace minecraft:light

execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^5 ^ ^2 ^5 light[level=9] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^6 ^ ^2 ^6 light[level=9] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^7 ^ ^2 ^7 light[level=9] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^8 ^ ^2 ^8 light[level=9] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^9 ^ ^2 ^9 light[level=9] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^10 ^ ^2 ^10 light[level=7] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^11 ^ ^2 ^11 light[level=7] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^12 ^ ^2 ^12 light[level=7] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^13 ^ ^2 ^13 light[level=7] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^14 ^ ^2 ^14 light[level=7] replace air
execute at @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] as @a[nbt={SelectedItem:{id:"minecraft:carrot_on_a_stick",tag:{CustomModelData:58861}}},scores={flashlight=1}] run fill ^ ^2 ^15 ^ ^2 ^15 light[level=7] replace air
